name: ci
on: [push]

jobs:


  build:
    runs-on: ubuntu-latest
    environment: CI
    steps:

      - name: Greet everyone
        run: echo Hello, world!

      - name: Install ssh-vault
        run: |
          PACKAGING=amd64.deb
          LATEST_VERSION=$(curl -w "%{redirect_url}" -o /dev/null -s https://bintray.com/nbari/ssh-vault/ssh-vault/_latestVersion | sed 's|.*/||')
          curl -L -O "https://dl.bintray.com/nbari/ssh-vault/ssh-vault_${LATEST_VERSION}_${PACKAGING}"
          dpkg -i ssh-vault*.deb

      - name: Encrypt secrets
        run: |
          echo -e "\nMTURK_WORKER_ID\n$MTURK_WORKER_ID\nAWS_ACCESS_KEY_ID\n$AWS_ACCESS_KEY_ID\nAWS_SECRET_ACCESS_KEY\n$AWS_SECRET_ACCESS_KEY\nPYPI_API_TOKEN\n$PYPI_API_TOKEN\nCHANDLER_GITHUB_API_TOKEN\n$CHANDLER_GITHUB_API_TOKEN" |ssh-vault -u silviot create /tmp/avault
          cat /tmp/avault
        env:
          MTURK_WORKER_ID: ${{ secrets.MTURK_WORKER_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
          CHANDLER_GITHUB_API_TOKEN: ${{ secrets.CHANDLER_GITHUB_API_TOKEN }}
